### Arrays
NumPy arrays are used to store lists of numerical data and to represent vectors, matrices, and even tensors. NumPy arrays are designed to handle large data sets efficiently and with a minimum of fuss. The NumPy library has a large set of routines for creating, manipulating, and transforming NumPy arrays. NumPy functions, like sqrt and sin, are designed specifically to work with NumPy arrays. Core Python has an array data structure, but it’s not nearly as versatile, efficient, or useful as the NumPy array. 

In [1]:
import numpy as np

In [4]:
a = np.array([2,3,4])

In [5]:
a

array([2, 3, 4])

In [6]:
a.dtype

dtype('int64')

In [14]:
b = np.array([1.2, 3.5, 5.1])

In [16]:
b[0]

1.2

In [17]:
b[1]

3.5

In [8]:
b.dtype

dtype('float64')

In [9]:
a = np.array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [10]:
a = np.array([1,2,3,4])  # RIGHT

In [25]:
b = np.array([(1.5,2,3), (4,5,6)])

In [26]:
b.dtype

dtype('float64')

In [28]:
b[1]

array([ 4.,  5.,  6.])

In [27]:
b[0][1]

2.0

In [60]:
b = np.array([(1.5,2,3), (4,5,6)],dtype = 'int')

In [61]:
b[0][1]

2

In [62]:
b.sum()

21

In [63]:
b[1].sum()

15

In [64]:
b[0].sum()

6

In [65]:
b[0]

array([1, 2, 3])

In [66]:
b

array([[1, 2, 3],
       [4, 5, 6]])

#### arange

In [96]:
a = np.arange(15)

In [97]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
a.shape

(15,)

In [99]:
a.ndim

1

In [85]:
a.dtype.name

'int64'

In [86]:
a.size

15

In [87]:
type(a)

numpy.ndarray

In [89]:
b = np.arange(15, dtype = 'float')

In [91]:
b

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.])

In [92]:
a.dtype.name

'int64'

#### reshape

In [94]:
c = np.arange(15).reshape(3, 5)

In [95]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
c.dtype

dtype('int64')

In [101]:
c.ndim

2

In [102]:
c[1]

array([5, 6, 7, 8, 9])

In [105]:
 b = np.arange(12).reshape(4,3)

In [106]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [107]:
c = np.arange(24).reshape(2,3,4)         # 3d array

In [108]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### transposed

In [115]:
 d = np.arange(12).reshape(4,3)

In [116]:
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [117]:
d.shape

(4, 3)

In [119]:
t = d.T

In [122]:
t.shape

(3, 4)

#### flatten

In [124]:
a = np.array([[1,2], [3,4]])

In [125]:
a

array([[1, 2],
       [3, 4]])

In [126]:
r = a.flatten()

In [127]:
r

array([1, 2, 3, 4])

In [130]:
c = a.flatten('F')
#'F' means to flatten in column-major

In [131]:
c

array([1, 3, 2, 4])

#### concatenate

In [3]:
a = np.array([[1, 2], [3, 4]])

In [4]:
b = np.array([[5, 6]])

In [5]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

#### Identity :The identity array is a square array with ones on the main diagonal.



In [12]:
i1 = np.identity(3)

In [13]:
i1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [10]:
i2 = np.eye(3)


In [14]:
i2

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
### identity just calls eye so there is no difference

### zeros


In [20]:
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### ones

In [21]:
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### Full

In [23]:
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

#### Maths Operation

In [45]:
x = np.array([1, 2, 3, 4])

In [46]:
np.sum(x)

10

In [47]:
x.sum()

10

In [48]:
x.min()

1

In [49]:
x.max()

4

In [50]:
x.mean()

2.5

In [51]:
x = np.array([1, 2, 3, 1])

In [52]:
np.median(x)

1.5

#### Sum by rows and by columns

In [53]:
x = np.array([[1, 1], [2, 2]])

In [54]:
x

array([[1, 1],
       [2, 2]])

In [55]:
x.sum(axis=0)   # columns (first dimension)

array([3, 3])

In [56]:
x.sum(axis=1)   # rows (second dimension)

array([2, 4])

#### Floor


In [4]:
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [6]:
print np.floor(my_array)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### Ceil

In [7]:
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])


In [8]:
print np.ceil(my_array) 

[  2.   3.   4.   5.   6.   7.   8.   9.  10.]


#### Rint 

In [9]:
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])


In [10]:
print np.rint(my_array)

[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


#### Matrix operations 

In [41]:
a = np.array( [20,30,40,50] )

In [42]:
a

array([20, 30, 40, 50])

In [43]:
b = np.arange( 4 )

In [44]:
b

array([0, 1, 2, 3])

In [45]:
c = a+b


In [46]:
c

array([20, 31, 42, 53])

In [47]:
d= a-b

In [48]:
d

array([20, 29, 38, 47])

In [49]:
e = a*b


In [50]:
e

array([  0,  30,  80, 150])

In [51]:
f = a/b

/Users/aribahmehreen/.virtualenvs/keras_tf/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


In [52]:
f

array([ 0, 30, 20, 16])

In [53]:
A = np.array([[1,1], [0,1]])

In [54]:
A

array([[1, 1],
       [0, 1]])

In [55]:
B = np.array( [[2,0],[3,4]])

In [56]:
B

array([[2, 0],
       [3, 4]])

In [57]:
A*B

array([[2, 0],
       [0, 4]])

In [58]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [59]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

#### Inner 

In [ ]:
A = np.array([3, 2])
B = np.array([3, 4])

In [7]:
#3*3+2*4
np.inner(A, B) 

17

#### outer

In [9]:
#3*3 , 3*4
#2*3 , 2*4
np.outer(A, B) 

array([[ 9, 12],
       [ 6,  8]])

#### determinant of an array

In [10]:
print np.linalg.det([[1 , 2], [2, 1]])

-3.0


#### eigenvalues and right eigenvectors of a square array

In [12]:
vals, vecs = np.linalg.eig([[1 , 2], [2, 1]])

In [13]:
vals

array([ 3., -1.])

In [14]:
vecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

### inverse of a matrix (multiplicative)

In [17]:
np.linalg.inv([[1 , 2], [2, 1]]) 

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])